apiVersion: v1
kind: Secret
metadata:
  name: cm-sa-creds
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  "key.json": {{ .Values.config.auth.json | b64enc }}